#!/bin/bash
# Copyright 2017 Aleksander Gajewski <adiog@brainfuck.pl>
#   created:  czw, 9 lis 2017, 01:59:58
#   modified: czw, 9 lis 2017, 03:36:30

# BASH_CLEANUP {{{
BASH_CLEANUP_FILE=`mktemp`
trap BASH_CLEANUP EXIT

function BASH_CLEANUP() {
  BASH_CLEANUP_FILE_REV=`mktemp`
  tac $BASH_CLEANUP_FILE > $BASH_CLEANUP_FILE_REV
  . $BASH_CLEANUP_FILE_REV
  rm $BASH_CLEANUP_FILE $BASH_CLEANUP_FILE_REV
}

function BASH_FINALLY() {
  echo "$*" >> $BASH_CLEANUP_FILE
}

function BASH_MKTEMP() {
  BASH_TMP=`mktemp`
  echo "rm $BASH_TMP" >> $BASH_CLEANUP_FILE
  echo $BASH_TMP
}

function BASH_MKTEMP_DIR() {
  BASH_TMP=`mktemp -d`
  echo "rm -fr $BASH_TMP" >> $BASH_CLEANUP_FILE
  echo $BASH_TMP
}
# }}}

function verbose()
{
  [[ -n "$VERBOSE" ]] && read
}

base=$1
tars=$2

target_git_repo=$base

if [[ ! -d $target_git_repo ]]; then
  (
  mkdir -p $target_git_repo
  cd $target_git_repo
  git init
  )
fi

TEMP=`BASH_MKTEMP_DIR`

for tarpath in `ls -v -1 $tars/*`; do
  tarreal=$(realpath $tarpath)
  tarfile=$(basename $tarpath)
  tarname=${tarfile/.tar.gz/}
  version=${tarname/${base}-/}
  
  echo "MAKE_GIT: adding $version"
  verbose

  untargz $tarreal $TEMP
  (cd $target_git_repo && git rm -fr * > /dev/null)
  mv $TEMP/$tarname/* $target_git_repo/
  (cd $target_git_repo && git add . && git commit -m "$version" && git tag -a "$version" -m "$version")
  echo "MAKE_GIT: added $version"
  verbose
  
  rm -fr $TEMP/*
done

