#!/bin/bash

ARCHIVE=$(realpath $1)
TARGET=${2:-${1/.tar.gz/}}
if [[ $TARGET != "." ]]; then
	if [[ -e $TARGET || -d $TARGET ]]; then
		echo "You may override something. Are you sure you know what you are doing?"
	  return
	fi
	mkdir -p $TARGET
fi	
(cd $TARGET && tar -xkzvf $ARCHIVE)

